api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        security: null
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/UserManagement/Entity']