doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        # Removed deprecated and invalid options
        auto_mapping: false  # Disable auto-mapping since we're using explicit mappings
        mappings:
            # Adjust the mapping paths to point to your DDD directories
            App:
                type: attribute
                is_bundle: false
                # Define the directories where your entities are stored
                dir: '%kernel.project_dir%/src/UserManagement/Entity'
                prefix: 'App\UserManagement\Entity'
                alias: UserManagement
            Company:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/CompanyManagement/Entity'
                prefix: 'App\CompanyManagement\Entity'
                alias: CompanyManagement
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
